CREATE EXTENSION IF NOT EXISTS "pgcrypto"

CREATE TABLE IF NOT EXIST schema_migrations(
    migration_id SERIAL PRIMARY KEY,
    FILE_NAME VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);
